const questions = [
  { question: "If it rains tomorrow, we ___ at home.", answers: ["will stay"] },
  { question: "If I had enough money, I ___ a new laptop.", answers: ["would buy"] },
  { question: "If she studies hard, she ___ the test.", answers: ["will pass"] },
  { question: "If I had known about the problem, I would have ___ her.", answers: ["helped"] },
  { question: "If he doesn't hurry, he ___ the train.", answers: ["will miss"] },
  { question: "If I were you, I ___ that mistake.", answers: ["would not make", "wouldn't make"] },
  { question: "If they had invited us, we ___ to the party.", answers: ["would have gone"] },
  { question: "If we ___ earlier, we wouldn't be late now.", answers: ["had left"] },
  { question: "If she had taken the advice, she ___ this situation.", answers: ["would have avoided"] },
  { question: "If I ___ a better plan, everything would be easier.", answers: ["had"] },
  { question: "If I finish my work early, I ___ a walk in the park.", answers: ["will take"] },
  { question: "If you heat ice, it ___.", answers: ["melts"] },
  { question: "If he had studied more, he ___ the exam.", answers: ["would have passed"] },
  { question: "If we ___ enough food, we will have a picnic.", answers: ["have"] },
  { question: "If I ___ rich, I would buy a house.", answers: ["were"] },
  { question: "If she doesn't call, I ___ worried.", answers: ["will be"] },
  { question: "If I had known your address, I ___ you a letter.", answers: ["would have sent"] },
  { question: "If they arrive late, we ___ the meeting.", answers: ["will start"] },
  { question: "If I ___ taller, I could reach the shelf.", answers: ["were"] },
  { question: "If he had listened carefully, he ___ the instructions.", answers: ["would have understood"] },
  { question: "If I see her tomorrow, I ___ her the news.", answers: ["will tell"] },
  { question: "If they had not forgotten the map, we ___ lost.", answers: ["would not have gotten", "wouldn't have gotten"] },
  { question: "If I ___ more time, I would read this book.", answers: ["had"] },
  { question: "If she practices regularly, she ___ better at tennis.", answers: ["will play"] },
  { question: "If you ___ the door, the cat will escape.", answers: ["leave"] },
  { question: "If I had prepared better, I ___ less nervous.", answers: ["would have been"] },
  { question: "If he ___ harder, he would win the game.", answers: ["worked"] },
  { question: "If I find her address, I ___ send her a gift.", answers: ["will"] },
  { question: "If they had not missed the bus, they ___ on time.", answers: ["would have arrived"] },
  { question: "If I ___ you, I would take that opportunity.", answers: ["were"] },
  { question: "If we start now, we ___ finish before lunch.", answers: ["will"] },
  { question: "If she had apologized, he ___ forgiven her.", answers: ["would have"] },
  { question: "If it ___ sunny tomorrow, we will go to the beach.", answers: ["is"] },
  { question: "If I had seen the sign, I ___ entered the street.", answers: ["would not have"] },
  { question: "If he ___ more careful, he wouldn't make mistakes.", answers: ["were"] },
  { question: "If I ___ earlier, I wouldn't be late.", answers: ["had left"] },
  { question: "If they ___ enough money, they could travel around the world.", answers: ["had"] },
  { question: "If she practices more, she ___ win the competition.", answers: ["will"] },
  { question: "If I had asked him, he ___ helped me.", answers: ["would have"] },
  { question: "If you ___ now, you will catch the bus.", answers: ["leave"] },
  { question: "If I ___ a car, I could drive to the mountains.", answers: ["had"] },
  { question: "If he had not been tired, he ___ finished the work.", answers: ["would have"] },
  { question: "If I see him, I ___ remind him about the meeting.", answers: ["will"] },
  { question: "If they ___ earlier, they wouldn't have missed the train.", answers: ["had left"] },
  { question: "If she had studied harder, she ___ the scholarship.", answers: ["would have got", "would have received"] },
  { question: "If we ___ more time, we could visit the museum.", answers: ["had"] },
  { question: "If I ___ a better job, I would be happier.", answers: ["had"] },
  { question: "If he ___ more careful, he wouldn't have broken the vase.", answers: ["were"] },
  { question: "If I ___ known about the traffic, I would have left earlier.", answers: ["had"] },
  { question: "If it ___ cold tonight, we will stay inside.", answers: ["is"] },
  { question: "If I ___ you, I would take a break.", answers: ["were"] },
  { question: "If they had not argued, they ___ gone to the party.", answers: ["would have"] },
  { question: "If she ___ more patient, she will solve the problem.", answers: ["is"] },
  { question: "If I had practiced more, I ___ performed better.", answers: ["would have"] }
];
